services:
  - type: web
    name: social-wavez-server
    runtime: node
    plan: free
    buildCommand: npm ci --only=production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
